name: Python Selenium CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      xvfb:
        image: selenium/standalone-chrome:latest
        ports:
          - 4444:4444

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        AE_TEST_EMAIL: ${{ secrets.AE_TEST_EMAIL }}
        AE_TEST_PASSWORD: ${{ secrets.AE_TEST_PASSWORD }}
      run: |
        xvfb-run pytest automation_exercise_tests/tests --maxfail=1 --disable-warnings -v
